// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[] = SECRET_SSID; // Network SSID (name)
const char PASS[] = SECRET_PASS; // Network password (use for WPA, or use as key for WEP)

void onBuiltinLedChange();
void onHour1Change();
void onHour1HallChange();
void onHour2Change();
void onHour2HallChange();
void onMinute1Change();
void onMinute1HallChange();
void onMinute2Change();
void onMinute2HallChange();
void onCalibrateChange();

CloudLight builtin_led;
int hour_1;
int hour_1_hall;
int hour_2;
int hour_2_hall;
int minute_1;
int minute_1_hall;
int minute_2;
int minute_2_hall;
bool calibrate;

void initProperties()
{

  ArduinoCloud.addProperty(builtin_led, READWRITE, ON_CHANGE, onBuiltinLedChange);
  ArduinoCloud.addProperty(hour_1, READWRITE, ON_CHANGE, onHour1Change);
  ArduinoCloud.addProperty(hour_1_hall, READWRITE, ON_CHANGE, onHour1HallChange);
  ArduinoCloud.addProperty(hour_2, READWRITE, ON_CHANGE, onHour2Change);
  ArduinoCloud.addProperty(hour_2_hall, READWRITE, ON_CHANGE, onHour2HallChange);
  ArduinoCloud.addProperty(minute_1, READWRITE, ON_CHANGE, onMinute1Change);
  ArduinoCloud.addProperty(minute_1_hall, READWRITE, ON_CHANGE, onMinute1HallChange);
  ArduinoCloud.addProperty(minute_2, READWRITE, ON_CHANGE, onMinute2Change);
  ArduinoCloud.addProperty(minute_2_hall, READWRITE, ON_CHANGE, onMinute2HallChange);
  ArduinoCloud.addProperty(calibrate, READWRITE, ON_CHANGE, onCalibrateChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
